apiVersion: v1
kind: Secret
metadata:
  name: gitea
  labels:
    app.kubernetes.io/name: gitea
type: Opaque
stringData:
  app.ini: |-

    [cache]
    ADAPTER = memcache
    ENABLED = true
    HOST = memcached:11211

    [database]
    DB_TYPE = postgres
    HOST = postgresql:5432
    NAME = gitea
    PASSWD = postgrespassword
    USER = gitea

    [metrics]
    ENABLED = false

    [security]
    INSTALL_LOCK = true

    [server]
    APP_DATA_PATH = /data
    DOMAIN = git.antisozializer.org
    ENABLE_PPROF = false
    HTTP_PORT = 3000
    PROTOCOL = http
    ROOT_URL = http://git.antisozializer.org
    SSH_DOMAIN = git.antisozializer.org
    SSH_LISTEN_PORT = 22
    SSH_PORT = 22