apiVersion: v1
kind: Secret
metadata:
  name: gitea-init
  labels:
    app: gitea
    app.kubernetes.io/name: gitea
type: Opaque
stringData:
  init_gitea.sh: |-
    #!/bin/bash

    mkdir -p /data/git/.ssh
    chmod -R 700 /data/git/.ssh
    mkdir -p /data/gitea/conf
    cp /etc/gitea/conf/app.ini /data/gitea/conf/app.ini
    chmod a+rwx /data/gitea/conf/app.ini
    nc -v -w2 -z postgresql 5432 && \
    su git -c ' \
    set -x; \
    gitea migrate; \
    gitea admin create-user --username  mloitzl --password "giteapassword" --email mloitzl@local.domain --admin --must-change-password=false \
    || \
    gitea admin change-password --username mloitzl --password "giteapassword"; \
    '